[package]
name = "nixbuild"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 3
lto = "fat"